Clean up.
Signed-off-by: Mirjam Aulbach <mirjam.aulbach@aiven.io>

diff --git a/.github/workflows/end-to-end-tests.yaml b/.github/workflows/end-to-end-tests.yaml
--- a/.github/workflows/end-to-end-tests.yaml
+++ b/.github/workflows/end-to-end-tests.yaml
@@ -1,3 +1,5 @@
+# The workflow can be triggered manually.
+# It will build and deploy Klaw and run E2E tests against it.
 name: E2E tests
 on:
 
@@ -35,6 +37,7 @@ jobs:
         with:
           node-version: ${{ steps.versions.outputs.NODE_VERSION }}
 
+      # PNPM needs to be available for coral in the build
       - name: Setup pnpm
         uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4
         with:
@@ -55,9 +58,6 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-pnpm-store-
 
-      - name: Check Docker Compose version
-        run: docker-compose --version
-
       - name: Set up JDK
         uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
         with:
@@ -66,12 +66,12 @@ jobs:
           cache: maven
 
       - name: Build Klaw
-        run:  docker-scripts/klaw-docker.sh --dev-ui-tests
+        working-directory: ./e2e
+        run: pnpm __build-klaw
 
-      - name: Check Container Logs
-        run: docker logs klaw-core
-
-      - name: Log Container Network Address
+      # @TODO: make sure Klaw always runs on a predictable address
+      # then this step is unnecessary
+      - name: Get container network address
         id: containerIp
         shell: bash
         run: |
@@ -83,27 +83,41 @@ jobs:
             echo "CONTAINER_IP=$container_ip" >> $GITHUB_OUTPUT
           else
             echo "Container not found or not running"
+            exit 1
           fi
           
-
-      - name: Check if Klaw is reachable
+      # This step may be brittle. The service in the container seems not to
+      # be immediately ready to accept connections, so the retry makes sure
+      # we're giving it (hopefully) enough time to be ready.
+      - name: Make sure Klaw is reachable
         run:  |
-          retries=5  # Set the number of retries
-          interval=5  # Set the initial retry interval in seconds
-          max_interval=30  # Set the maximum retry interval in seconds
+          retries=5  # Number of retries
+          interval=5  # Initial retry interval in seconds
+          max_interval=30  # Max retry interval in seconds
+          success=false
           
+          echo "Check that Klaw is running on ${{ steps.containerIp.outputs.CONTAINER_IP}}:9097"
+  
           for ((i = 0; i < retries; i++)); do
-            curl "${{ steps.containerIp.outputs.CONTAINER_IP}}:9097" && break  # Try the curl command, exit loop on success
-            
-            # Sleep before the next retry with exponential backoff
-            sleep $interval
-            interval=$((interval * 2))
-            
-            # Ensure the interval doesn't exceed the maximum
-            if [ $interval -gt $max_interval ]; then
-              interval=$max_interval
-            fi
+            if curl --fail --silent "${{ steps.containerIp.outputs.CONTAINER_IP}}:9097"; then
+            success=true
+            break 
+          fi
+          
+          # Sleep before the next retry with exponential backoff
+          sleep $interval
+          interval=$((interval * 2))
+        
+          # Ensure the interval doesn't exceed the maximum
+          if [ $interval -gt $max_interval ]; then
+            interval=$max_interval
+          fi
           done
+          
+          if [ "$success" = false ]; then
+            echo "Klaw is not reachable 😭"
+            exit 1 
+          fi
 
       - name: Install dependencies
         working-directory: ./e2e
@@ -114,12 +128,16 @@ jobs:
         run: pnpm playwright install --with-deps chromium
 
       - name: Run Playwright tests
+        id: playwright-test-run
         working-directory: ./e2e
-        run: BASE_URL=http://${{ steps.containerIp.outputs.CONTAINER_IP }}:9097 pnpm test
+        run: BASE_URL=http://${{ steps.containerIp.outputs.CONTAINER_IP }}:9097 pnpm __test
 
       - name: Upload Playwright artifacts
         uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
-        if: always()
+        # Upload whether steps before where a failure, but only when the playwright tests did run
+        # This way we make sure we don't attempt to upload files that are not there, bc.
+        # for example the build has failed.
+        if:  ${{ always() && steps.playwright-test-run.status == 'completed' }}
         with:
           name: playwright-report
           path: playwright-report/
